### ISSUE TITLE
make the =source trigger to =sauce

### ISSUE THREAD

**Issue by ghost** [nikhilvayeda/bhendi-bot-3#6]
make the `=source` trigger to `=sauce`

**Comment by prashantrahul141** [comment]
it'll be better if both are kept,
one as an alias

**Comment by ghost** [comment]
ok

**Comment by prashantrahul141** [comment]
done it in : https://github.com/nikhilvayeda/bhendi-bot-3/commit/07271d85ea9a51975c06d779a05f23c6ed24a9b9
